### ISSUE TITLE
YouTubers dataset in config.yaml

### ISSUE THREAD

**Issue by MorganCZY** [franroldans/tfm-franroldan-wav2pix#5]
Hi, paths about "Youtubers dataset" are all blank, so the repo cannot be run. Could you provide related paths or csv files?

**Comment by franroldans** [comment]
Hi @MorganCZY 

First of all, thanks for having interest about this project and apologies for my delayed response. I refer to what I answered in [this ](https://github.com/franroldans/tfm-franroldan-wav2pix/issues/4) issue. We still don't have the permission from all the individuals that appear in the dataset, so for the moment sharing the data would not be legal in our country. We are working to obtain this permissions from all of them. 

In case you still want to use this code, I will look for a sample of the paths I used, so you visualize how the dataset and correct the hardcoded parts.

In any case, I would recommend you to use the code you can find in this other [repo ](https://imatge-upc.github.io/wav2pix/) and add your issues there as this one is no longer maintained :) In this other repo you have two sample youtubers from whom we obtained the permission, and the code in there should be fully prepared to be run.

If there's anything more I can help you don't hesitate to contact me.
